### ISSUE TITLE
Still works?

### ISSUE THREAD

**Issue by regeleDavid900** [LuaGunsX/HerbertV1#1]
Hi.
I am asking you if this work. If it work please gimme me an email or respond this.
Now how this work on cheat engines for exemple SteamCE it will work? And if yes please tell me how. Thanks

**Comment by LuaGunsX** [comment]
Just use the loadstring.

**Comment by regeleDavid900** [comment]
There is an really serverside or an fe bypass? Btw I found this random
thats why I am asking

sâm., 20 apr. 2024, 02:34 LuaGunsX ***@***.***> a scris:
